clusterZone: "cluster.local"
renderHelmLabels: true
controller:
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  taglabel: jdk11
  imagePullPolicy: "Always"
  imagePullSecretName:
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  javaOpts: "-Xms2048m -Xmx2048m"
  fsGroup: 1000
  serviceType: ClusterIP
  adminSecret: true
  adminUser: "admin"
  adminPassword: Ch1p3r2021
sidecars:
  configAutoReload:
    enabled: true
    image: kiwigrid/k8s-sidecar:1.15.0
    imagePullPolicy: IfNotPresent
    reqRetryConnect: 10
agent:
  enabled: true
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
persistence:
  size: "200Gi"
  existingClaim: pvc-jenkins-home-3
networkPolicy:
  apiVersion: networking.k8s.io/v1
rbac:
  create: true
serviceAccount:
  name: cd-jenkins
